name: MLOps Stunting Pipeline

# Robot ini akan jalan setiap kali kamu push ke branch main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Robot mengambil kodemu dari GitHub
    - uses: actions/checkout@v3

    # 2. Robot menginstall Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    # 3. Robot menginstall library (sesuai requirements.txt)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # 4. Robot mencoba menjalankan Training (Test Run)
    # Tujuannya memastikan script train.py tidak error/crash
    - name: Test Training Script
      run: |
        python src/train.py --data-path data/data_balita.csv --model-path models/test_model.pkl

    # 5. (Opsional) Robot mengecek kualitas kode
    - name: Check Code Quality
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics